Algoritmo "DocesDaColmeia"

//Compra por quilo- Bolo
//Desconto (Desconto por situação)
//Quantidade de Unidades- Docinho


Var

opcao :  caractere



Inicio

escreval("~~~~~~~catalogo~~~~~~~")
escreval("1- Trufas.............R$ 8,00")
escreval("2- Bolo no Pote.......R$ 10,00")
escreval("3- Copo da felicidade.R$ 15,00")
escreval("4- Docinho............R$ 3,00")
escreval("5- Pudim..............R$ 25,00")
escreval("6- Cancelar")
escreval("7- Carrinho")

leia(opcao)


Fimalgoritmo