Algoritmo "Atividade 4"


Var

numero1,numero2, numero3,numero4,resultado:inteiro

Inicio

escreval ("Digite o 1º número")
leia (numero1)
limpaTela

escreval ("Digite o 2º número")
leia (numero2)
limpaTela

escreval ("Digite o 3º número")
leia (numero3)
limpaTela

escreval ("Digite o 4º número")
leia (numero4)
limpaTela

  resultado <- numero1 + numero2 + numero3 + numero4
      escreval("A soma dos números é: ",resultado)


Fimalgoritmo