Algoritmo "recepcao"



Var
nome, email: caractere
idade: inteiro


Inicio
escreval("Seja Bem Vindo! Por favor digite seu nome:")
leia(nome)
limpatela()

escreval("Digite a sua idade:")
leia(idade)
limpatela()

escreval("Digite o seu email:")
leia(email)
limpatela()

escreval("Dados registrados com sucesso!")
escreval("~~~~~~~~~~~~~~")
escreval("Usuario: ",nome)
escreval("Idade: ", idade)
escreval("Email: ", email)
escreval("~~~~~~~~~~~~~~")



Fimalgoritmo