Algoritmo "semnome"

Var

time1:caractere
time2:caractere
ngols1:inteiro
ngols2:inteiro

Inicio

escreval("Digite o 1º Time:")
leia(time1)
limpaTela()

escreval("Número de Gols:")
leia(ngols1)
limpaTela()

escreval("Digite o 2º time:")
leia(time2)
limpaTela()

escreval("Número de Gols:")
leia(ngols2)
limpaTela()

se(ngols1 > ngols2)entao

   escreval(time1, "É O VENCEDOR!")

senao
      escreval(time2, "É O VENCEDOR!")


fimSe

Fimalgoritmo