Algoritmo "Área do retângulo"

Var

 base,altura,area:real

Inicio
//Entrada:receber base e altura

 escreval("Qual é a base do retângulo? (m2)" )
 leia(base)
 limpaTela()
 
 escreval("Qual é a altura do retângulo? (m2)")
 leia(altura)
 limpaTela()

//Processamento : calcular a area

area <- base*altura
limpaTela


//Saida: retornar a area calculada

escreval ("A area em m2 é de :" , area)

Fimalgoritmo